### ISSUE TITLE
Fine dining in Berlin

### ISSUE THREAD

**Issue by norbert** [norbert/travel#1]
This needs to happen.

/cc @dylanegan @lstoll

**Comment by lstoll** [comment]
Dos Palilos?

**Comment by dylanegan** [comment]
@norbert sure thing. What day?

**Comment by norbert** [comment]
@lstoll did you get a reservation for tonight?

**Comment by lstoll** [comment]
I don't think so, waiting to hear back. But seems unlikely.

**Comment by norbert** [comment]
Too bad. Guess this issue will stay open a little longer.

**Comment by dylanegan** [comment]
Next week!

**Comment by norbert** [comment]
@dylanegan I'll still be in Cape Town or Amsterdam then!

**Comment by lstoll** [comment]
When are you back?

**Comment by norbert** [comment]
Probably around the 17th.

**Comment by norbert** [comment]
Next week! Returning tomorrow.

**Comment by lstoll** [comment]
We're all away next week.. Maybe late the week after?

**Comment by norbert** [comment]
Thursday it is!

/cc @sr @vangberg

**Comment by vangberg** [comment]
Oh, that looks pretty good actually. Nice.

**Comment by dylanegan** [comment]
13, 17 or 20 courses? They have 19:00, 19:30 and 20:30 available. It takes between 4 and 5 hours depending on the course amount.

**Comment by sr** [comment]
+1 20 courses. 19:30 sounds great to me.

On 31 Oct 2012, at 17:21, Dylan Egan notifications@github.com wrote:

13, 17 or 20 courses? They have 19:00, 19:30 and 20:30 available. It takes
between 4 and 5 hours depending on the course amount.

—
Reply to this email directly or view it on
GitHubhttps://github.com/norbert/travel/issues/1#issuecomment-9951290.

**Comment by vangberg** [comment]
Same as @sr

**Comment by norbert** [comment]
Yeah, 20 courses at 19:30 sounds perfect.

**Comment by dylanegan** [comment]
Should all be confirmed in. They haven't responded, but I assume the table was available.

**Comment by norbert** [comment]
Twenty courses will be sufficient for now.

**Comment by dylanegan** [comment]
Fucking nailed it.

**Comment by sr** [comment]
:hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger::hamburger:
