### ISSUE TITLE
Plan Amsterdam-Berlin invasion

### ISSUE THREAD

**Issue by norbert** [norbert/travel#10]
From the 8th until...?

/cc @Juice10 @elphabatizing @dylanegan

**Comment by Juice10** [comment]
I'm leaving on the 12th again

**Comment by dylanegan** [comment]
I'm here all weekend.

**Comment by norbert** [comment]
@Juice10 which day are we having the birthday dinner?

Two options:
- [Schneeweiss](http://www.schneeweiss-berlin.de/schneeweiss.html)
- [Katz Orange](http://www.katzorange.com/en)

**Comment by Juice10** [comment]
friday evening

**Comment by lstoll** [comment]
Always be beard-offing

**Comment by norbert** [comment]
@lstoll word.

@Juice10 how many people?

**Comment by Juice10** [comment]
## People in for dinner

Norbert
Claudia
Emily
Angela + Boyfriend
Justin
Catherina

@lstoll (dinner or after dinner drinks?)

## After dinner drinks

Dylan +1 after dinner for drinks

(PS. @dylanegan @norbert; Ben from D74 says hi)

**Comment by dylanegan** [comment]
@Juice10 ah cool. Tell him I say hi too. Which bar did he go to?

Also @sr is in town too so he'll probably join for drinks.

**Comment by dylanegan** [comment]
Do you have a drinks location yet? If you head to Schneeweiß then [Antlered Bunny](https://www.facebook.com/TheAntleredBunny) is close.

**Comment by Juice10** [comment]
lets do http://restaurant-nansen.de at 7:30 and afterwards Antlered Bunny
