### ISSUE TITLE
Dinner at Margaux

### ISSUE THREAD

**Issue by norbert** [norbert/travel#11]
http://margaux-berlin.de/
http://contemporaryfoodlab.com/journal/2013/11/interview-with-michael-hoffmann/

/cc @dylanegan

**Comment by dylanegan** [comment]
Not sure. Maybe an email to the restaurant to find out?

**Comment by norbert** [comment]
"February 2014" apparently. Should be possible to find a date before then.

**Comment by norbert** [comment]
Fixed via @dylanegan.

**Comment by dylanegan** [comment]
Vemazing!
