### ISSUE TITLE
Explore Cape Town

### ISSUE THREAD

**Issue by norbert** [norbert/travel#6]
This is finally happening.

/cc @smn @atmos

**Comment by atmos** [comment]
![](http://img.becomegorgeous.com/user/a/7/1/a/crissy78/photos/my_photos/to_see_the_world_in_a_grain_of_sand-11313.jpg)

**Comment by norbert** [comment]
![](http://i.imgur.com/ThyTk.gif)

**Comment by smn** [comment]
Sweet! Looking forward. @atmos, when will you be visiting CT again?

**Comment by norbert** [comment]
Success.
