### ISSUE TITLE
Southern Brunch

### ISSUE THREAD

**Issue by norbert** [norbert/travel#8]
There will be chicken and waffles on the 30th in Amsterdam.

For those who have to miss out on the deep fried goodness due to dietary restraints something else will be served.

Also bourbon.

/cc @manfred @alloy @Juice10

**Comment by elphabatizing** [comment]
Yes.

**Comment by Manfred** [comment]
Ah, I thought this was on Saturday for some reason. Not sure if I'll be back in Amsterdam around noon.

**Comment by norbert** [comment]
@Manfred we said around 14:00, hopefully that works for you.

**Comment by ptegelaar** [comment]
Ik Ben dan in Polen dude! NYE in Danzig... Doe ze maar de groeten daar & tot snel!

Von meinem iPhone gesendet

Am 26.12.2012 um 14:40 schrieb Norbert Crombach notifications@github.com:

**Comment by norbert** [comment]
That was a lot of chicken.
