### ISSUE TITLE
Dinner at &samhoud

### ISSUE THREAD

**Issue by norbert** [norbert/travel#9]
/cc @dylanegan @Manfred @elphabatizing

**Comment by dylanegan** [comment]
Ja. I am in town May 30 to June 3. Danke.

**Comment by dylanegan** [comment]
Just checked the website, seems like there are still plenty of spots for four people on the 30th.

**Comment by dylanegan** [comment]
Also oyster happy hour on Saturday June 1.

**Comment by norbert** [comment]
So @elphabatizing is out, @Juice10 will still be recovering from Japan and @Manfred is busy on the weekend.

Three people at 20:00 on the 30th?

**Comment by dylanegan** [comment]
@norbert who is the third? An yeah, I'm good with whatever.

**Comment by norbert** [comment]
@dylanegan that would be us two and @Manfred.

**Comment by norbert** [comment]
Reservation confirmed.

**Comment by norbert** [comment]
That was a lot of foam.

**Comment by dylanegan** [comment]
I'm still in for oysters and burger on Saturday. Otherwise it should've been a single :star: place.

**Comment by norbert** [comment]
Yeah. Might go back some time if they keep both stars because that will only happen if they step up the service.
